AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.1

Style/StringLiterals:
  EnforcedStyle: double_quotes

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - Rakefile
    - "*.gemspec"
