# frozen_string_literal: true

source "https://rubygems.org"

gemspec
gem "rbxx", path: "../.."
gem "minitest", "~> 5.0"
gem "rake", "~> 13.0"
gem "rake-compiler", "~> 1.2"
gem "rake-compiler-dock", "~> 1.10", require: false
