// Generated by scripts/amalgamate.rb. Do not edit directly.
#pragma once

// BEGIN rbxx/detail/ruby_include.hpp

#if defined(_MSC_VER)
#ifndef NOMINMAX
#define NOMINMAX
#endif
#pragma warning(push)
#pragma warning(disable : 4127 4244 4267 4996)
#else
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wconversion"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#pragma GCC diagnostic ignored "-Wsign-conversion"
#pragma GCC diagnostic ignored "-Wunused-parameter"
#endif

#include <ruby.h>
#include <ruby/thread.h>
#include <ruby/version.h>

#if defined(_MSC_VER)
#pragma warning(pop)
#else
#pragma GCC diagnostic pop
#endif

#define RBXX_RUBY_VERSION_MAJOR RUBY_API_VERSION_MAJOR
#define RBXX_RUBY_VERSION_MINOR RUBY_API_VERSION_MINOR
#define RBXX_RUBY_VERSION_TEENY RUBY_API_VERSION_TEENY

static_assert(RUBY_API_VERSION_MAJOR >= 3, "rbxx requires CRuby 3.1 or newer");
// END rbxx/detail/ruby_include.hpp

// BEGIN rbxx/version.hpp

#define RBXX_VERSION_MAJOR 0
#define RBXX_VERSION_MINOR 1
#define RBXX_VERSION_PATCH 0
#define RBXX_VERSION "0.1.0"

namespace rbxx {

/// @brief The rbxx semantic version string.
/// @code auto version = rbxx::version; @endcode
inline constexpr const char* version = RBXX_VERSION;

} // namespace rbxx
// END rbxx/version.hpp

// BEGIN rbxx/rbxx.hpp

// END rbxx/rbxx.hpp
