// Generated by scripts/amalgamate.rb. Do not edit directly.
#pragma once

// BEGIN rbxx/detail/ruby_include.hpp

#if defined(_MSC_VER)
#ifndef NOMINMAX
#define NOMINMAX
#endif
#pragma warning(push)
#pragma warning(disable : 4127 4244 4267 4996)
#else
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wconversion"
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#pragma GCC diagnostic ignored "-Wsign-conversion"
#pragma GCC diagnostic ignored "-Wunused-parameter"
#endif

#include <ruby.h>
#include <ruby/thread.h>
#include <ruby/version.h>

#if defined(_MSC_VER)
#pragma warning(pop)
#else
#pragma GCC diagnostic pop
#endif

#define RBXX_RUBY_VERSION_MAJOR RUBY_API_VERSION_MAJOR
#define RBXX_RUBY_VERSION_MINOR RUBY_API_VERSION_MINOR
#define RBXX_RUBY_VERSION_TEENY RUBY_API_VERSION_TEENY

static_assert(RUBY_API_VERSION_MAJOR >= 3, "rbxx requires CRuby 3.1 or newer");
// END rbxx/detail/ruby_include.hpp

// BEGIN rbxx/value.hpp


#include <type_traits>

namespace rbxx {

/// @brief A zero-overhead, non-owning view of a Ruby VALUE.
/// @code rbxx::value nil{Qnil}; @endcode
class value {
public:
  /// @brief Constructs a nil value.
  constexpr value() noexcept = default;

  /// @brief Wraps a raw Ruby VALUE without pinning it.
  /// @code auto wrapped = rbxx::value{Qtrue}; @endcode
  explicit constexpr value(VALUE raw) noexcept : raw_(raw) {}

  /// @brief Returns the wrapped Ruby VALUE.
  /// @code VALUE raw = wrapped.raw(); @endcode
  [[nodiscard]] constexpr VALUE raw() const noexcept { return raw_; }

  /// @brief Returns whether this value is nil.
  /// @code if (wrapped.is_nil()) { return; } @endcode
  [[nodiscard]] constexpr bool is_nil() const noexcept { return NIL_P(raw_); }

  /// @brief Returns whether this value is a Ruby boolean.
  [[nodiscard]] constexpr bool is_bool() const noexcept { return raw_ == Qtrue || raw_ == Qfalse; }

  /// @brief Returns whether this value is a Ruby Integer.
  [[nodiscard]] bool is_integer() const noexcept { return RB_INTEGER_TYPE_P(raw_); }

  /// @brief Returns whether this value is a Ruby Float.
  [[nodiscard]] bool is_float() const noexcept { return RB_TYPE_P(raw_, T_FLOAT); }

  /// @brief Returns whether this value is a Ruby String.
  [[nodiscard]] bool is_string() const noexcept { return RB_TYPE_P(raw_, T_STRING); }

  /// @brief Returns whether this value is a Ruby Symbol.
  [[nodiscard]] bool is_symbol() const noexcept { return SYMBOL_P(raw_); }

  /// @brief Returns whether this value is a Ruby Array.
  [[nodiscard]] bool is_array() const noexcept { return RB_TYPE_P(raw_, T_ARRAY); }

  /// @brief Returns whether this value is a Ruby Hash.
  [[nodiscard]] bool is_hash() const noexcept { return RB_TYPE_P(raw_, T_HASH); }

private:
  VALUE raw_ = Qnil;
};

static_assert(std::is_trivially_copyable_v<value>);
static_assert(sizeof(value) == sizeof(VALUE));

/// @brief Keeps a temporary Ruby value visible to the conservative GC.
/// @code rbxx::gc_guard(value); @endcode
inline void gc_guard(value guarded) noexcept {
  VALUE raw = guarded.raw();
  RB_GC_GUARD(raw);
}

} // namespace rbxx
// END rbxx/value.hpp

// BEGIN rbxx/object.hpp


#include <memory>
#include <utility>

namespace rbxx {
namespace detail {

class object_cell {
public:
  explicit object_cell(VALUE initial) noexcept : stored_(initial) {
    rb_gc_register_address(&stored_);
  }

  object_cell(const object_cell&) = delete;
  object_cell& operator=(const object_cell&) = delete;

  ~object_cell() noexcept { rb_gc_unregister_address(&stored_); }

  [[nodiscard]] VALUE raw() const noexcept { return stored_; }

private:
  VALUE stored_;
};

} // namespace detail

/// @brief A copyable, movable RAII handle that pins a Ruby object across GC and compaction.
/// @code rbxx::object pinned{rbxx::value{ruby_value}}; @endcode
class object {
public:
  /// @brief Constructs an empty handle representing nil.
  object() noexcept = default;

  /// @brief Pins the supplied Ruby value.
  /// @code rbxx::object pinned{rbxx::value{Qtrue}}; @endcode
  explicit object(value initial) : cell_(std::make_shared<detail::object_cell>(initial.raw())) {}

  /// @brief Pins the supplied raw Ruby VALUE.
  explicit object(VALUE initial) : object(value{initial}) {}

  object(const object&) noexcept = default;
  object(object&&) noexcept = default;
  object& operator=(const object&) noexcept = default;
  object& operator=(object&&) noexcept = default;
  ~object() = default;

  /// @brief Returns the pinned object as a non-owning value view.
  /// @code rbxx::value current = pinned.get(); @endcode
  [[nodiscard]] value get() const noexcept { return value{raw()}; }

  /// @brief Returns the current raw VALUE, updated after compaction.
  [[nodiscard]] VALUE raw() const noexcept { return cell_ ? cell_->raw() : Qnil; }

  /// @brief Returns whether the handle is empty or pins nil.
  [[nodiscard]] bool is_nil() const noexcept { return NIL_P(raw()); }

  /// @brief Releases this handle's ownership of the pin.
  /// @code pinned.reset(); @endcode
  void reset() noexcept { cell_.reset(); }

private:
  std::shared_ptr<detail::object_cell> cell_;
};

} // namespace rbxx
// END rbxx/object.hpp

// BEGIN rbxx/exception.hpp


#include <exception>
#include <new>
#include <stdexcept>
#include <string>

namespace rbxx {

/// @brief A C++ exception that preserves the original Ruby exception object.
/// @code catch (const rbxx::ruby_error& error) { error.reraise(); } @endcode
class ruby_error : public std::exception {
public:
  /// @brief Pins a Ruby exception for propagation through C++ frames.
  explicit ruby_error(value exception) : exception_(exception) {}
  explicit ruby_error(VALUE exception) : exception_(exception) {}

  /// @brief Returns a stable description for C++ diagnostics.
  [[nodiscard]] const char* what() const noexcept override { return "Ruby exception"; }

  /// @brief Returns the preserved Ruby exception.
  [[nodiscard]] value exception() const noexcept { return exception_.get(); }

  /// @brief Returns the Ruby exception class name.
  [[nodiscard]] std::string ruby_class_name() const;

  /// @brief Returns the Ruby exception message.
  [[nodiscard]] std::string message() const;

  /// @brief Throws a copy so the outer Ruby boundary can transparently re-raise it.
  [[noreturn]] void reraise() const { throw *this; }

private:
  object exception_;
};

namespace detail {

inline VALUE exception_class_name(VALUE exception) { return rb_class_name(CLASS_OF(exception)); }

inline VALUE exception_message(VALUE exception) {
  VALUE message = rb_funcall(exception, rb_intern("message"), 0);
  return rb_obj_as_string(message);
}

inline std::string protected_exception_string(VALUE exception, VALUE (*function)(VALUE)) {
  int state = 0;
  VALUE string = rb_protect(function, exception, &state);
  if (state != 0) {
    VALUE nested = rb_errinfo();
    rb_set_errinfo(Qnil);
    throw ruby_error(nested);
  }
  return std::string(RSTRING_PTR(string), static_cast<std::size_t>(RSTRING_LEN(string)));
}

struct exception_creation {
  VALUE klass;
  const char* message;
};

inline VALUE create_exception(VALUE opaque) {
  auto* creation = reinterpret_cast<exception_creation*>(opaque);
  return rb_exc_new_cstr(creation->klass, creation->message);
}

inline VALUE make_exception(VALUE klass, const char* message) noexcept {
  exception_creation creation{klass, message};
  int state = 0;
  VALUE result = rb_protect(create_exception, reinterpret_cast<VALUE>(&creation), &state);
  if (state == 0) {
    return result;
  }

  result = rb_errinfo();
  rb_set_errinfo(Qnil);
  return result;
}

/// @brief Converts the active C++ exception into a Ruby exception VALUE without raising it.
/// @code catch (...) { pending = rbxx::detail::translate_current_exception(); } @endcode
inline VALUE translate_current_exception() noexcept {
  try {
    throw;
  } catch (const ruby_error& error) {
    return error.exception().raw();
  } catch (const std::invalid_argument& error) {
    return make_exception(rb_eArgError, error.what());
  } catch (const std::out_of_range& error) {
    return make_exception(rb_eRangeError, error.what());
  } catch (const std::range_error& error) {
    return make_exception(rb_eRangeError, error.what());
  } catch (const std::bad_alloc& error) {
    return make_exception(rb_eNoMemError, error.what());
  } catch (const std::domain_error& error) {
    return make_exception(rb_eMathDomainError, error.what());
  } catch (const std::exception& error) {
    return make_exception(rb_eRuntimeError, error.what());
  } catch (...) {
    return make_exception(rb_eRuntimeError, "unknown C++ exception");
  }
}

} // namespace detail

inline std::string ruby_error::ruby_class_name() const {
  return detail::protected_exception_string(exception_.raw(), detail::exception_class_name);
}

inline std::string ruby_error::message() const {
  return detail::protected_exception_string(exception_.raw(), detail::exception_message);
}

} // namespace rbxx
// END rbxx/exception.hpp

// BEGIN rbxx/extension.hpp


#if defined(_WIN32)
#define RBXX_EXPORT __declspec(dllexport)
#else
#define RBXX_EXPORT __attribute__((visibility("default")))
#endif

#define RBXX_EXTENSION(name)                                                                       \
  static void rbxx_init_body_##name();                                                             \
  extern "C" RBXX_EXPORT void Init_##name() {                                                      \
    VALUE rbxx_pending_exception = Qnil;                                                           \
    try {                                                                                          \
      rbxx_init_body_##name();                                                                     \
      return;                                                                                      \
    } catch (...) {                                                                                \
      rbxx_pending_exception = ::rbxx::detail::translate_current_exception();                      \
    }                                                                                              \
    rb_exc_raise(rbxx_pending_exception);                                                          \
  }                                                                                                \
  static void rbxx_init_body_##name()
// END rbxx/extension.hpp

// BEGIN rbxx/protect.hpp


#include <exception>
#include <functional>
#include <optional>
#include <tuple>
#include <type_traits>
#include <utility>

namespace rbxx {
namespace detail {

template <typename Function, typename... Args> struct protect_payload {
  using function_type = std::decay_t<Function>;
  using result_type = std::invoke_result_t<function_type&, std::decay_t<Args>&...>;
  using stored_result = std::conditional_t<std::is_void_v<result_type>, bool, result_type>;

  function_type function;
  std::tuple<std::decay_t<Args>...> args;
  std::optional<stored_result> result;
  std::exception_ptr cpp_exception;
};

template <typename Payload> VALUE protect_trampoline(VALUE opaque) noexcept {
  auto* payload = reinterpret_cast<Payload*>(opaque);
  try {
    if constexpr (std::is_void_v<typename Payload::result_type>) {
      std::apply(payload->function, payload->args);
      payload->result.emplace(true);
    } else {
      payload->result.emplace(std::apply(payload->function, payload->args));
    }
  } catch (...) {
    payload->cpp_exception = std::current_exception();
  }
  return Qnil;
}

} // namespace detail

/// @brief Invokes a Ruby C API operation through rb_protect and converts longjmp to ruby_error.
/// @code VALUE string = rbxx::protect(rb_utf8_str_new_cstr, "safe"); @endcode
template <typename Function, typename... Args> auto protect(Function&& function, Args&&... args) {
  using payload_type = detail::protect_payload<Function, Args...>;
  static_assert(!std::is_reference_v<typename payload_type::result_type>,
                "rbxx::protect does not support reference return types");

  payload_type payload{std::forward<Function>(function),
                       std::tuple<std::decay_t<Args>...>{std::forward<Args>(args)...}, std::nullopt,
                       nullptr};
  int state = 0;
  rb_protect(detail::protect_trampoline<payload_type>, reinterpret_cast<VALUE>(&payload), &state);

  if (state != 0) {
    VALUE exception = rb_errinfo();
    rb_set_errinfo(Qnil);
    throw ruby_error(exception);
  }
  if (payload.cpp_exception) {
    std::rethrow_exception(payload.cpp_exception);
  }

  if constexpr (std::is_void_v<typename payload_type::result_type>) {
    return;
  } else {
    return std::move(*payload.result);
  }
}

} // namespace rbxx
// END rbxx/protect.hpp

// BEGIN rbxx/type_caster.hpp


#include <concepts>
#include <cstddef>
#include <limits>
#include <string>
#include <string_view>
#include <type_traits>
#include <utility>

namespace rbxx {

/// @brief Customization point for conversion between Ruby and C++ values.
/// @code template <> struct rbxx::type_caster<MyType> { /* load/dump/matches */ }; @endcode
template <typename T, typename Enable = void> struct type_caster;

/// @brief True when T can be converted to a Ruby value.
template <typename T>
concept to_ruby_convertible = requires(const std::remove_cvref_t<T>& input) {
  { type_caster<std::remove_cvref_t<T>>::dump(input) } -> std::convertible_to<value>;
};

/// @brief True when a Ruby value can be converted to T.
template <typename T>
concept from_ruby_convertible =
    requires(value input) { type_caster<std::remove_cvref_t<T>>::load(input); };

namespace detail {

template <typename T> constexpr std::string_view type_name() noexcept {
#if defined(_MSC_VER)
  constexpr std::string_view signature = __FUNCSIG__;
  constexpr std::string_view prefix = "type_name<";
  const auto start = signature.find(prefix) + prefix.size();
  return signature.substr(start, signature.find(">(void)", start) - start);
#else
  constexpr std::string_view signature = __PRETTY_FUNCTION__;
  constexpr std::string_view prefix = "T = ";
  const auto start = signature.find(prefix) + prefix.size();
  const auto end = signature.find_first_of("];", start);
  return signature.substr(start, end - start);
#endif
}

[[noreturn]] inline void throw_type_error(const char* expected, value actual) {
  const char* actual_name = rb_obj_classname(actual.raw());
  std::string message = "rbxx: expected ";
  message += expected;
  message += ", got ";
  message += actual_name;
  throw ruby_error(make_exception(rb_eTypeError, message.c_str()));
}

template <typename Integer> Integer load_integer(value input) {
  if constexpr (std::is_signed_v<Integer>) {
    const auto converted = protect(rb_num2ll, input.raw());
    constexpr auto minimum = static_cast<LONG_LONG>(std::numeric_limits<Integer>::min());
    constexpr auto maximum = static_cast<LONG_LONG>(std::numeric_limits<Integer>::max());
    if (converted < minimum || converted > maximum) {
      throw std::range_error("rbxx: Integer is outside the target C++ signed integer range");
    }
    return static_cast<Integer>(converted);
  } else {
    const auto converted = protect(rb_num2ull, input.raw());
    constexpr auto maximum = static_cast<unsigned LONG_LONG>(std::numeric_limits<Integer>::max());
    if (converted > maximum) {
      throw std::range_error("rbxx: Integer is outside the target C++ unsigned integer range");
    }
    return static_cast<Integer>(converted);
  }
}

template <typename Integer> value dump_integer(Integer input) {
  if constexpr (std::is_signed_v<Integer>) {
    return value{protect(rb_ll2inum, static_cast<LONG_LONG>(input))};
  } else {
    return value{protect(rb_ull2inum, static_cast<unsigned LONG_LONG>(input))};
  }
}

inline const char* checked_string_pointer(value input) {
  if (!input.is_string()) {
    throw_type_error("String", input);
  }
  VALUE raw = input.raw();
  return protect([raw]() mutable {
    VALUE string = raw;
    return StringValueCStr(string);
  });
}

inline value dump_utf8(const char* bytes, std::size_t size) {
  if (size > static_cast<std::size_t>(std::numeric_limits<long>::max())) {
    throw std::length_error("rbxx: String is too large for CRuby");
  }
  return value{protect(rb_utf8_str_new, bytes, static_cast<long>(size))};
}

} // namespace detail

template <typename T>
struct type_caster<T, std::enable_if_t<std::is_integral_v<T> && !std::is_same_v<T, bool>>> {
  static constexpr std::string_view name = "Integer";

  /// @brief Loads a range-checked C++ integer.
  static T load(value input) { return detail::load_integer<T>(input); }

  /// @brief Dumps a C++ integer as a Ruby Integer.
  static value dump(T input) { return detail::dump_integer(input); }

  /// @brief Returns whether the Ruby value is an Integer.
  static bool matches(value input) noexcept { return input.is_integer(); }
};

template <> struct type_caster<bool> {
  static constexpr std::string_view name = "Boolean";

  static bool load(value input) {
    if (!input.is_bool()) {
      detail::throw_type_error("true or false", input);
    }
    return input.raw() == Qtrue;
  }

  static value dump(bool input) noexcept { return value{input ? Qtrue : Qfalse}; }
  static bool matches(value input) noexcept { return input.is_bool(); }
};

template <> struct type_caster<float> {
  static constexpr std::string_view name = "Float";
  static float load(value input) { return static_cast<float>(protect(rb_num2dbl, input.raw())); }
  static value dump(float input) {
    return value{protect(rb_float_new, static_cast<double>(input))};
  }
  static bool matches(value input) noexcept { return input.is_float() || input.is_integer(); }
};

template <> struct type_caster<double> {
  static constexpr std::string_view name = "Float";
  static double load(value input) { return protect(rb_num2dbl, input.raw()); }
  static value dump(double input) { return value{protect(rb_float_new, input)}; }
  static bool matches(value input) noexcept { return input.is_float() || input.is_integer(); }
};

template <> struct type_caster<const char*> {
  static constexpr std::string_view name = "String";
  static const char* load(value input) { return detail::checked_string_pointer(input); }
  static value dump(const char* input) {
    if (input == nullptr) {
      detail::throw_type_error("non-null C string", value{Qnil});
    }
    return value{protect(rb_utf8_str_new_cstr, input)};
  }
  static bool matches(value input) noexcept { return input.is_string(); }
};

template <> struct type_caster<std::string> {
  static constexpr std::string_view name = "String";
  static std::string load(value input) {
    return std::string(detail::checked_string_pointer(input));
  }
  static value dump(const std::string& input) {
    return detail::dump_utf8(input.data(), input.size());
  }
  static bool matches(value input) noexcept { return input.is_string(); }
};

template <> struct type_caster<std::string_view> {
  static constexpr std::string_view name = "String";
  static std::string_view load(value input) {
    const char* bytes = detail::checked_string_pointer(input);
    return std::string_view(bytes, static_cast<std::size_t>(RSTRING_LEN(input.raw())));
  }
  static value dump(std::string_view input) {
    return detail::dump_utf8(input.data(), input.size());
  }
  static bool matches(value input) noexcept { return input.is_string(); }
};

template <> struct type_caster<value> {
  static constexpr std::string_view name = "Object";
  static value load(value input) noexcept { return input; }
  static value dump(value input) noexcept { return input; }
  static bool matches(value) noexcept { return true; }
};

template <> struct type_caster<object> {
  static constexpr std::string_view name = "Object";
  static object load(value input) { return object{input}; }
  static value dump(const object& input) noexcept { return input.get(); }
  static bool matches(value) noexcept { return true; }
};

/// @brief Converts a C++ value to Ruby with an actionable missing-caster diagnostic.
/// @code rbxx::value result = rbxx::to_ruby(42); @endcode
template <typename T> value to_ruby(T&& input) {
  using converted_type = std::remove_cvref_t<T>;
  static_assert(to_ruby_convertible<converted_type>,
                "rbxx: type has no type_caster; bind it with def_class<T>() or specialize "
                "rbxx::type_caster<T>");
  return type_caster<converted_type>::dump(std::forward<T>(input));
}

/// @brief Converts a Ruby value to C++ with an actionable missing-caster diagnostic.
/// @code int result = rbxx::from_ruby<int>(ruby_value); @endcode
template <typename T> std::remove_cvref_t<T> from_ruby(value input) {
  using converted_type = std::remove_cvref_t<T>;
  static_assert(from_ruby_convertible<converted_type>,
                "rbxx: type has no type_caster; bind it with def_class<T>() or specialize "
                "rbxx::type_caster<T>");
  return type_caster<converted_type>::load(input);
}

} // namespace rbxx
// END rbxx/type_caster.hpp

// BEGIN rbxx/version.hpp

#define RBXX_VERSION_MAJOR 0
#define RBXX_VERSION_MINOR 1
#define RBXX_VERSION_PATCH 0
#define RBXX_VERSION "0.1.0"

namespace rbxx {

/// @brief The rbxx semantic version string.
/// @code auto version = rbxx::version; @endcode
inline constexpr const char* version = RBXX_VERSION;

} // namespace rbxx
// END rbxx/version.hpp

// BEGIN rbxx/rbxx.hpp

// END rbxx/rbxx.hpp
