# frozen_string_literal: true

require "fileutils"
require "pathname"

ROOT = Pathname(__dir__).parent
INCLUDE_ROOT = ROOT.join("include")
ENTRYPOINT = INCLUDE_ROOT.join("rbxx", "rbxx.hpp")
OUTPUT = ROOT.join("single_include", "rbxx", "rbxx.hpp")
LOCAL_INCLUDE = /^\s*#include\s+<(?<path>rbxx\/[A-Za-z0-9_\/.-]+)>\s*$/

class HeaderGraph
  def initialize(include_root)
    @include_root = include_root
    @temporary = {}
    @permanent = {}
    @ordered = []
  end

  def order(entrypoint)
    visit(entrypoint)
    @ordered
  end

  private

  def visit(path)
    path = path.realpath
    return if @permanent[path]
    raise "include cycle detected at #{path}" if @temporary[path]

    @temporary[path] = true
    local_dependencies(path).each { |dependency| visit(dependency) }
    @temporary.delete(path)
    @permanent[path] = true
    @ordered << path
  end

  def local_dependencies(path)
    path.each_line.filter_map do |line|
      match = LOCAL_INCLUDE.match(line)
      next unless match

      dependency = @include_root.join(match[:path])
      raise "missing local include #{match[:path]} from #{path}" unless dependency.file?

      dependency
    end
  end
end

def render_header
  graph = HeaderGraph.new(INCLUDE_ROOT)
  headers = graph.order(ENTRYPOINT)
  body = headers.map do |header|
    relative = header.relative_path_from(INCLUDE_ROOT)
    content = header.each_line.reject do |line|
      line.match?(LOCAL_INCLUDE) || line.match?(/^\s*#pragma once\s*$/)
    end.join
    "// BEGIN #{relative}\n#{content.rstrip}\n// END #{relative}"
  end.join("\n\n")

  <<~HEADER
    // Generated by scripts/amalgamate.rb. Do not edit directly.
    #pragma once

    #{body}
  HEADER
end

def check(output)
  abort "#{OUTPUT} is missing; run rake amalgamate" unless OUTPUT.file?
  return if OUTPUT.binread == output

  abort "#{OUTPUT} is stale; run rake amalgamate"
end

rendered = render_header
if ARGV == ["--check"]
  check(rendered)
elsif ARGV.empty?
  FileUtils.mkdir_p(OUTPUT.dirname)
  OUTPUT.binwrite(rendered)
else
  abort "usage: #{File.basename($PROGRAM_NAME)} [--check]"
end
